### ISSUE TITLE
Breaking change from 2.0.2 - no longer returns all extensions for mime type

### ISSUE THREAD

**Issue by paviad** [lettucebo/MimeTypeMap.List#19]
Library version 2.0.2 used to return a list of all extensions for a mime type, this version does not, it arbitrarily picks one extension.

For example for `application/vnd.ms-excel` has `slk` `xls` `xlm` and others, but currently only `xls` is returned, and for no good reason.

*EDIT* I suggest maybe putting the 'default' one at index 0, and the rest following.

**Comment by lettucebo** [comment]
Hi 

Please use 2.0.3 for now, it should behavior just like previous version, I only publish the StringComparer.OrdinalIgnoreCase commit

For 3.0.0, I'm trying to resolve the issue right now

**Comment by lettucebo** [comment]
Hi

I have update the 2.1.0, it's the same mechanism with pervious version, just change the way to manage mapping list
