### ISSUE TITLE
minor performance suggestion with StringComparison

### ISSUE THREAD

**Issue by sandromastronardi** [lettucebo/MimeTypeMap.List#5]
Hi,

I have a small performance suggestion regarding this line:
https://github.com/lettucebo/MimeTypeMap.List/blob/72bc3553ac0b70e5e4aac7ff862d95fd78a038ae/MimeTypeMap.List/MimeTypeMap.cs#L59

I would like to suggest to use Equals with StringComparison.OrdinalIgnoreCase.... it performs better and isn't 2 operations on one string...

ref: https://stackoverflow.com/questions/1660192/string-comparison-stra-tolower-strb-tolower-or-stra-equalsstrb-stringcom

it could make a difference in big applications where lots of files are being parsed ;-)

Love the library...

**Comment by lettucebo** [comment]
Will publish a new version this week
